Resources:
   myInstance1:
     Type: 'AWS::EC2::Instance'
     Properties: 
        ImageId: ami-04b70fa74e45c3917
        InstanceType: t3.micro
        KeyName: "maccess"
        SubnetId: subnet-01b4410840cbaec87
        SecurityGroupIds:
          - sg-0486f08458887bf50
   ElasticIP: 
     Type: AWS::EC2::EIP
     Properties:
       InstanceId: !Ref myInstance1